# Generated by Django 5.1.1 on 2024-10-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.TextField()),
                ('division', models.TextField(null=True)),
                ('serialnumber', models.TextField(null=True)),
                ('cs_manufacturer', models.TextField(null=True)),
                ('cs_model', models.TextField(null=True)),
                ('cs_systemfamily', models.TextField(null=True)),
                ('restriction', models.SmallIntegerField(null=True)),
                ('owner', models.TextField(null=True)),
                ('cs_json', models.JSONField(null=True)),
                ('check_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsbStor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regid', models.IntegerField()),
                ('regnum', models.CharField(max_length=20)),
                ('regdate', models.DateField(null=True)),
                ('serialnum', models.CharField(max_length=200)),
                ('divname', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
            ],
        ),
    ]
