# Generated by Django 5.1.1 on 2024-10-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='check_date',
        ),
        migrations.RemoveField(
            model_name='host',
            name='cs_json',
        ),
    ]
