# Generated by Django 5.1.1 on 2024-10-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_remove_host_check_date_remove_host_cs_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='check_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='cs_json',
            field=models.JSONField(null=True),
        ),
    ]
