# Generated by Django 5.1.1 on 2024-10-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0003_host_check_date_host_cs_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='av_json',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='eset_json',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='wa_json',
            field=models.JSONField(null=True),
        ),
    ]
