# Generated by Django 5.1.1 on 2024-10-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0004_host_av_json_host_eset_json_host_wa_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='usb_json',
            field=models.JSONField(null=True),
        ),
    ]
