# Generated by Django 5.1.1 on 2024-10-19 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0005_host_usb_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_acro', models.TextField()),
                ('common_name', models.TextField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('middle_name', models.TextField()),
                ('family_name', models.TextField()),
                ('military_rank', models.TextField(null=True)),
                ('phone_number', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='division_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checks.division'),
        ),
        migrations.AddField(
            model_name='usbstor',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checks.division'),
        ),
    ]
