# Generated by Django 5.1.1 on 2024-10-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0006_division_person_host_division_id_usbstor_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
