# Generated by Django 5.1.1 on 2024-10-19 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0007_host_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='division',
        ),
    ]
