# Generated by Django 5.1.1 on 2024-10-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0008_remove_host_division'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='division_id',
            new_name='division',
        ),
    ]
