# Generated by Django 5.1.1 on 2024-10-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0009_rename_division_id_host_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='restriction',
            field=models.SmallIntegerField(choices=[(0, 'Нетаємно'), (3, 'Таємно'), (4, 'ДСК')], default=0),
        ),
    ]
