# Generated by Django 5.1.1 on 2024-10-20 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0010_alter_host_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checks.person'),
        ),
    ]
