# Generated by Django 5.1.1 on 2024-10-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0011_host_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='WPK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
    ]
