# Generated by Django 5.1.1 on 2024-11-03 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0012_wpk'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usbstor',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usbstor',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checks.person'),
        ),
        migrations.AddField(
            model_name='usbstor',
            name='restriction',
            field=models.SmallIntegerField(choices=[(0, 'Нетаємно'), (3, 'Таємно'), (4, 'ДСК')], default=0),
        ),
        migrations.AddField(
            model_name='usbstor',
            name='stype',
            field=models.CharField(default='USB', max_length=50),
        ),
    ]
