# Generated by Django 5.1.1 on 2025-03-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0016_rename_physical_disk_json_host_physical_disks_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='allowed_storage',
            field=models.ManyToManyField(to='checks.usbstor'),
        ),
    ]
