# Generated by Django 5.1.1 on 2025-03-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0017_host_allowed_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usbstor',
            name='product',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usbstor',
            name='vendor',
            field=models.IntegerField(default=0),
        ),
    ]
